### ISSUE TITLE
handle message failed

### ISSUE THREAD

**Issue by Jiangluyu** [DaiShengSheng/lifeRestart_bot#7]
ERROR: <ActionFailed, retcode=103>
Traceback (most recent call last):
  File "/home/plugins/hoshinobot/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "/home/plugins/hoshinobot/HoshinoBot/hoshino/service.py", line 217, in wrapper
    return await func(bot, event)
  File "/home/plugins/hoshinobot/HoshinoBot/hoshino/modules/lifeRestart_bot/__init__.py", line 91, in remake
    await bot.send_group_forward_msg(group_id=ev['group_id'], messages=mes_list)
  File "/usr/local/lib/python3.8/dist-packages/aiocqhttp/__init__.py", line 223, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/lib/python3.8/dist-packages/aiocqhttp/api_impl.py", line 186, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/usr/local/lib/python3.8/dist-packages/aiocqhttp/api_impl.py", line 161, in call_action
    return _handle_api_result(
  File "/usr/local/lib/python3.8/dist-packages/aiocqhttp/api_impl.py", line 51, in _handle_api_result
    raise ActionFailed(retcode=result.get('retcode'))

依赖已经安装了，请问是什么问题呀

**Comment by DaiShengSheng** [comment]
这个应该是合并消息发送失败了，尝试更新一下到最新版本的go-cqhttp，或者拆成多条消息发送

**Comment by Jiangluyu** [comment]
OK 我试试
2021年9月8日 +0800 12:34 黛笙笙 ***@***.***>，写道：
